# Generated by Django 5.2.1 on 2025-05-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_researchpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
