# Generated by Django 5.2.1 on 2025-05-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='created_at',
            field=models.DateField(),
        ),
    ]
