# Generated by Django 5.2.1 on 2025-05-12 14:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
