# Generated by Django 5.2.1 on 2025-05-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_content_alter_researchpaper_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Collectif CGED', max_length=100),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='author',
            field=models.CharField(default='Collectif CGED', max_length=100),
        ),
    ]
