# Generated by Django 5.2.1 on 2025-05-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_author_alter_researchpaper_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
