# Generated by Django 5.2.1 on 2025-05-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_views_researchpaper_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
